default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: project_management_app_development
  host: db
  port: 5432
  username: postgres

test:
  <<: *default
  database: project_management_app_test
  host: db
  port: 5432
  username: postgres

production:
  <<: *default
  database: project_management_app_production
